name: pharm_health
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  expansion_tile_card: ^2.0.0
  flutter_screenutil: ^5.0.0+2
  fluttertoast: ^8.0.7
  get_it: ^7.1.3
  google_fonts: ^2.1.0
  http: ^0.13.3
  intl: ^0.17.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
